## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as numpy

###  creating array from list

In [8]:
arr_1d = numpy.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = numpy.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs numpy array

In [10]:
py_list = [1,3,4,5,6]
print("python list multiply by 2: ", py_list * 2)

numpy_array = numpy.array([1,2,3])
print("numpy array multiply by 2: ", numpy_array * 2)


python list multiply by 2:  [1, 3, 4, 5, 6, 1, 3, 4, 5, 6]
numpy array multiply by 2:  [2 4 6]


## creating array from scratch

In [18]:
zeros = numpy.zeros((3, 4))
print(zeros)

ones = numpy.ones((3, 4))
print(ones)

full = numpy.full((2,2),7)
print(full)

random = numpy.random.random((2,3))
print(random)

sequence = numpy.arange(0, 30, 5)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.41313371 0.24439854 0.51217369]
 [0.71919705 0.8726075  0.54455567]]
[ 0  5 10 15 20 25]


## transpose the array

In [5]:
array_11  = numpy.array([[1,2,3],[4,5,6]])
print(array_11)
print(array_11.shape)
print(array_11.ndim)
print(array_11.size)
print(array_11.dtype)
array_11.transpose()
print(array_11.transpose())


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
[[1 4]
 [2 5]
 [3 6]]


## Numpy Array operations 

In [5]:
indexArray = numpy.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", indexArray[2:7])

print("With step", indexArray[1:7:2])
print("Negative indexing", indexArray[-3])
print("Negative indexing", indexArray[-3:])
print("Negative indexing", indexArray[-5:-1])


Basic Slicing [3 4 5 6 7]
With step [2 4 6]
Negative indexing 8
Negative indexing [ 8  9 10]
Negative indexing [6 7 8 9]


In [3]:
arr_2d = numpy.array([[1, 2, 3], 
                      [4, 5, 6],
                        [7, 8, 9]])
# index starts with 0 so output will be 2nd row and 3rd column
print("Specific element",arr_2d[1, 2])

print("Get full row", arr_2d[0, :])
print("Get full column", arr_2d[:, 1])                      

Specific element 6
Get full row [1 2 3]
Get full column [2 5 8]


## Sorting 

In [9]:
unsorted_array = numpy.array([3,66,77,3,5,11,1,6,3])
print("Unsorted array", unsorted_array)
sorted_array = numpy.sort(unsorted_array)
print("Sorted array", sorted_array)

arr_2d_unsorted = numpy.array([[3, 7, 2],
                             [6, 4, 121],
                             [9, 1, 5]])
print("Unsorted array", arr_2d_unsorted)
print("Sorted 2D array by column\n", numpy.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row\n", numpy.sort(arr_2d_unsorted, axis=1))

Unsorted array [ 3 66 77  3  5 11  1  6  3]
Sorted array [ 1  3  3  3  5  6 11 66 77]
Unsorted array [[  3   7   2]
 [  6   4 121]
 [  9   1   5]]
Sorted 2D array by column
 [[  3   1   2]
 [  6   4   5]
 [  9   7 121]]
Sorted 2D array by row
 [[  2   3   7]
 [  4   6 121]
 [  1   5   9]]


## Filter

In [13]:
numbers = numpy.arange(1, 11)
print("Numbers: ", numbers)

even_numbers = numbers[numbers % 2 == 0] # you can provide expression in the brackets, which will be evaluated 
print("Even numbers: ", even_numbers)

odd_numbers = numbers[numbers % 2 != 0]
print("Odd numbers: ", odd_numbers)

Numbers:  [ 1  2  3  4  5  6  7  8  9 10]
Even numbers:  [ 2  4  6  8 10]
Odd numbers:  [1 3 5 7 9]


## Filter with mask

In [ ]:
numbers_for_mask = numpy.arange(1, 11)
mask =  numbers_for_mask > 5  # mask is expression which will be evaluated to True or False (kind of linq in C#)
print("Numbers for mask: ", numbers_for_mask)
print("Mask: ", mask)
print("Numbers greater than 5: ", numbers_for_mask[mask]) # you can use mask to filter the array

# assing values using boolean mask
numbers_for_mask[numbers_for_mask > 5] = 0 # all numbers greater than 5 will be set to 0
print("Numbers after assignment using mask: ", numbers_for_mask)


Numbers for mask:  [ 1  2  3  4  5  6  7  8  9 10]
Mask:  [False False False False False  True  True  True  True  True]
Numbers greater than 5:  [ 6  7  8  9 10]
Numbers after assignment using mask:  [1 2 3 4 5 0 0 0 0 0]
Numbers for indexing:  [11 12 13 14 15 16 17 18 19 20]


In [23]:
# indexing vs where()
numbers_for_indexing = numpy.arange(11, 21)
print("Numbers for indexing: ", numbers_for_indexing)

indices = [0,2,4,6] # you can provide list of indices to get values from the array
print("Indices: ", indices)
print("Numbers for indexing using indices: ", numbers_for_indexing[indices]) # you can use list of indices to filter the array

where_result = numpy.where(numbers_for_indexing > 15) # where() will return the indices of the elements that satisfy the condition
print("Where result: ", where_result) # it will return tuple of arrays, one for each dimension of the array

print("Numbers for indexing using where: ", numbers_for_indexing[where_result]) # you can use where() to filter the array


Numbers for indexing:  [11 12 13 14 15 16 17 18 19 20]
Indices:  [0, 2, 4, 6]
Numbers for indexing using indices:  [11 13 15 17]
Where result:  (array([5, 6, 7, 8, 9]),)
Numbers for indexing using where:  [16 17 18 19 20]


In [ ]:
# you can use where() to assign values based on condition
# in block (condition, x(if true), y(false)) if condition is True, x will be assigned, else y will be assigned, kind of c# ternary operator a > b ? a : b
condition_array  = numpy.where(numbers_for_indexing > 15, numbers_for_indexing*2, numbers_for_indexing) 
print("Condition array: ", condition_array) # all numbers greater than 15 will be set to 0

Condition array:  [11 12 13 14 15 32 34 36 38 40]


## Adding and removing data
